[package]
name = "nilo-lang"
version = "0.2.0"
description = "Examples for the Nilo language repository"
entry = "examples/main.nilo"

[exports]
math_tools = "examples/math_tools.nilo"
messages = "examples/messages.nilo"
